# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

index:
    path: /
    controller: App\Controller\DefaultController::index
    
form_loisir:
    path: /loisir/create
    controller: App\Controller\LoisirController::create

form_loisir_edit:
    path: /loisir/edit/{id}
    controller: App\Controller\LoisirController::edit

valid_loisir:
    path: /loisir/valid
    controller: App\Controller\LoisirController::valid